# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: ayo

before:
  hooks:
    - go mod tidy

builds:
  - id: ayo
    main: ./cmd/ayo
    binary: ayo
    ldflags:
      - -s -w
      - -X github.com/alexcabrera/ayo/internal/version.Version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"

brews:
  - name: ayo
    repository:
      owner: alexcabrera
      name: homebrew-tap
    homepage: "https://github.com/alexcabrera/ayo"
    description: "A command-line tool for running AI agents"
    directory: Formula
